yr=int(input("Enter the year: "))
gen=str(input("Enter the genre: "))
alb=str(input("Enter the album: "))
ttl=str(input("Enter the song title: "))
art=str(input("Enter the artist: "))

print("-----------------------------------------")
print("SONG DETAILS")
print("-----------------------------------------")

print(f"Year released: ", yr)
print(f"Genre: ", gen)
print(f"Album: ", alb)
print(f"Song Title: ", ttl)
print(f"Artist: ", art)
